"""Write ZOO.md: the frequency structure of every grokked base run.

Run:  uv run python scripts/zoo_report.py [--runs-dir runs] [--out ZOO.md]

A "base run" is any runs/ directory with checkpoints and a config.json but no
distill.json/anneal.json. For each one, the final checkpoint's (p^2, p) logit
table is projected onto the normalized cos(w(a+b-c)) templates:

  - per-frequency strength: the signed template coefficient, and its share of
    the summed squared coefficient across all frequencies
  - key frequencies: those with share > KEY_SHARE (0.01)
  - how much of the centered logit table the a+b-c family explains at all

Within one model the frequency templates are orthogonal by construction, so
the interesting cosine overlaps are *between* runs: the report ends with the
pairwise cosine similarity of the runs' centered logit tables (equivalently,
the normalized dot product of their full frequency-coefficient structure —
near 0 means disjoint frequency sets) and the shared-key-freq counts.
"""

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from grok.config import Config  # noqa: E402
from grok.data import make_dataset, train_test_split  # noqa: E402
from grok.fourier import Fourier  # noqa: E402
from grok.model import Transformer  # noqa: E402
from grok.train import checkpoint_epochs  # noqa: E402
from grok import metrics as M  # noqa: E402

KEY_SHARE = 0.01  # a frequency is "key" if it holds >1% of the coefficient energy
MIN_TEST_ACC = 0.99  # runs below this never grokked; their "frequencies" are noise


def base_runs(runs_dir: Path):
    for d in sorted(runs_dir.iterdir()):
        if not (d / "config.json").exists() or not (d / "checkpoints").exists():
            continue
        if (d / "distill.json").exists() or (d / "anneal.json").exists():
            continue
        yield d


def analyze_run(run_dir: Path):
    cfg = Config.load(run_dir / "config.json")
    model = Transformer(cfg)
    epoch, ckpt = checkpoint_epochs(run_dir)[-1]
    model.load_weights(str(ckpt))

    tokens, labels = make_dataset(cfg)
    labels_np = np.array(labels)
    _, is_test = train_test_split(cfg)
    logits = M.all_logits(model, tokens)
    fourier = Fourier(cfg.p)

    coeffs = M.cos_w_product_a_plus_b_minus_c_coeffs(logits, fourier)
    share = coeffs**2 / (coeffs**2).sum()
    key = np.flatnonzero(share > KEY_SHARE) + 1  # frequencies are 1-indexed
    key = key[np.argsort(-share[key - 1])]

    centered = logits - logits.mean(axis=-1, keepdims=True)
    frac_explained = (coeffs**2).sum() / (centered**2).sum()

    return {
        "name": run_dir.name,
        "cfg": cfg,
        "epoch": epoch,
        "coeffs": coeffs,
        "share": share,
        "key_freqs": key,
        "frac_explained": frac_explained,
        "centered": centered,
        "test_acc": M.accuracy(logits, labels_np, mask=is_test),
        "test_ce": M.cross_entropy_high_precision(logits, labels_np, mask=is_test),
    }


def matrix_table(names, values, fmt):
    short = [n.replace("seed", "s") for n in names]
    lines = ["| | " + " | ".join(short) + " |",
             "|---|" + "---|" * len(names)]
    for name, row in zip(short, values):
        lines.append("| **" + name + "** | " + " | ".join(fmt(v) for v in row) + " |")
    return "\n".join(lines)


def write_report(runs, skipped, out_path: Path):
    lines = [
        "# Grokked model zoo",
        "",
        "Generated by `scripts/zoo_report.py` from each base run's final checkpoint.",
        "Strength is the signed coefficient of the normalized cos(w(a+b−c)) template",
        "in the (p², p) logit table; share is that coefficient's fraction of the",
        f"summed squared coefficients. Key frequencies hold > {KEY_SHARE:.0%} share.",
        "",
    ]
    if skipped:
        lines += [
            "Skipped (never grokked, test acc < "
            f"{MIN_TEST_ACC}): "
            + ", ".join(f"{r['name']} (epoch {r['epoch']}, acc {r['test_acc']:.3f})"
                        for r in skipped),
            "",
        ]
    lines += [
        "## Per-run frequency structure",
        "",
        "| run | init seed | data seed | epoch | test acc | test CE | # key freqs | key freqs (by share) | a+b−c frac of centered logits |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in runs:
        freq_str = ", ".join(str(f) for f in r["key_freqs"])
        lines.append(
            f"| {r['name']} | {r['cfg'].init_seed} | {r['cfg'].data_seed} | {r['epoch']} "
            f"| {r['test_acc']:.4f} | {r['test_ce']:.2e} | {len(r['key_freqs'])} "
            f"| {freq_str} | {r['frac_explained']:.3f} |"
        )

    lines += ["", "### Per-frequency strength", ""]
    for r in runs:
        lines += [f"**{r['name']}**", "", "| freq | strength | share |", "|---|---|---|"]
        for f in r["key_freqs"]:
            lines.append(f"| {f} | {r['coeffs'][f - 1]:.1f} | {r['share'][f - 1]:.3f} |")
        rest = 1.0 - r["share"][r["key_freqs"] - 1].sum()
        lines += [f"| (all other freqs) | — | {rest:.3f} |", ""]

    names = [r["name"] for r in runs]
    n = len(runs)
    cos = np.eye(n)
    shared = np.zeros((n, n), dtype=int)
    for i in range(n):
        shared[i, i] = len(runs[i]["key_freqs"])
        for j in range(i + 1, n):
            a, b = runs[i]["centered"].ravel(), runs[j]["centered"].ravel()
            cos[i, j] = cos[j, i] = a @ b / (np.linalg.norm(a) * np.linalg.norm(b))
            shared[i, j] = shared[j, i] = len(
                set(runs[i]["key_freqs"]) & set(runs[j]["key_freqs"])
            )

    lines += [
        "## Pairwise overlap between runs",
        "",
        "Cosine similarity of the centered logit tables — near 0 means the runs'",
        "frequency structures are essentially disjoint, so a distillation between",
        "them must build every teacher frequency from scratch:",
        "",
        matrix_table(names, cos, lambda v: f"{v:.3f}"),
        "",
        "Shared key frequencies (diagonal = each run's own count):",
        "",
        matrix_table(names, shared, str),
        "",
    ]
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({n} runs)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--runs-dir", default="runs")
    parser.add_argument("--out", default="ZOO.md")
    args = parser.parse_args()

    all_runs = [analyze_run(d) for d in base_runs(Path(args.runs_dir))]
    runs = [r for r in all_runs if r["test_acc"] >= MIN_TEST_ACC]
    skipped = [r for r in all_runs if r["test_acc"] < MIN_TEST_ACC]
    write_report(runs, skipped, Path(args.out))
